### ISSUE TITLE
Support Cargo -Z minimal-versions

### ISSUE THREAD

**Issue by chipsenkbeil** [chipsenkbeil/entity-rs#38]
Dependent on https://github.com/async-graphql/async-graphql/pull/392.

```yaml
  minimal-version:
    name: minimal-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-09-21
          override: true
      - name: Install cargo-hack
        run: cargo install cargo-hack
      - name: "check --all-features -Z minimal-versions"
        run: |
          # Remove dev-dependencies from Cargo.toml to prevent the next `cargo update`
          # from determining minimal versions based on dev-dependencies.
          cargo hack --remove-dev-deps --workspace
          # Update Cargo.lock to minimal version dependencies.
          cargo update -Z minimal-versions
          cargo hack check --all-features --workspace --no-dev-deps
```

Hitting some issues where transient dependencies are too old.

```toml
[build-dependencies]
# Using -Z minimal-versions fails with the async-graphql dependency as it
# has the follow dep chain of
#
# multer 1.2.2 -> mime 0.3.0 -> unicase 2.0.0 -> rustc_version 0.1.0 -> semver 0.1.0
#
# The semver version fails to compile and is ancient, so we are providing a
# requirement on a later version of the build dependency to enable using
# the minimal version check
rustc_version = "0.1.7"
semver = "0.1.20"                                                                          
```
